name: Update Files JSON

on:
  push:
    branches:
      - main

jobs:
  update_files_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2     

      - name: Update files.json
        run: |
          echo "{\"files\": [" > files.json
          cat files.txt | while read filename; do
            echo "\"$filename\"," >> files.json
          done
          sed -i '$ s/,$//' files.json
          echo "]}" >> files.json
          git config --global user.email "treble_l@hotmail.com"
          git config --global user.name "pinktit"
          git add files.json
          git commit -m "Update files.json" --quiet
          git push origin main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

