name: Update Files JSON

on:
  push:
    branches:
      - main

jobs:
  update_files_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List text files
        id: list-files
        run: |
          ls -d ./*.txt | sed -e "s/^.\///" > files.txt

      - name: Create files.json
        run: |
          echo "{\"files\": [" > files.json
          cat files.txt | while read filename; do
            echo "\"$filename\"," >> files.json
          done
          sed -i '$ s/,$//' files.json
          echo "]}" >> files.json

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Push changes to files.json
        run: |
          git add files.json
          git commit -m "Update files.json" --quiet
          git push origin main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
