name: Update Files JSON

on:
  push:
    branches:
      - main

jobs:
  update_files_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update files.json for both folders
        run: node scripts/update-files-json.js

      - name: Commit and push changes
        run: |
          git config --global user.name "rudy"
          git config --global user.email "treble_l@hotmail.com"
          git add cn/files.json tw/files.json
          if ! git diff --staged --quiet; then
            git commit -m "Update files.json in cn and tw folders" --quiet
            git pull --rebase origin main
            git push origin main
          fi
